# encoding: utf-8

desc "Must delete and recreate region table before run this task"
task recreate_comunes_and_regions: :environment do

  # Maybe you need to run:
  # Client.where.not(comune_id: nil).each{ |c| c.comune_id=nil; c.save;}
  # ShopInscription.where.not(comune_id: nil).each{ |s| s.comune_id=nil; s.save;}

  # Create Regions
  if Region.count == 0
    Region.create name: 'I - Tarapaca'
    Region.create name: 'II - Antofagasta'
    Region.create name: 'III - Atacama'
    Region.create name: 'IV - Coquimbo'
    Region.create name: 'V - Valparaiso'
    Region.create name: 'VI - Libertador Bernardo O\'Higgins'
    Region.create name: 'VII - Maule'
    Region.create name: 'VIII - Bio-bio'
    Region.create name: 'IX - Araucania'
    Region.create name: 'X - Los Lagos'
    Region.create name: 'XI -Aysen del General Carlos Ibañez del Campo'
    Region.create name: 'XII - Magallanes'
    Region.create name: 'XIII - Metropolitana'
    Region.create name: 'XIV - Los Rios'
    Region.create name: 'XV -Arica y Parinacota'
  end

  # Re-create all comunes
  # Comune.delete_all
  # id = 1
  # Comune.create desc_comuna: 'ÑIQUEN', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'ÑUÑOA', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'ALGARROBO', region_id: 5, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'ALHUE', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'ALTO BIOBIO', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'ALTO DEL CARMEN', region_id: 3, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'ALTO HOSPICIO', region_id: 1, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'ANCUD', region_id: 10, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'ANDACOLLO', region_id: 4, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'ANGOL', region_id: 9, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'ANTARTICA', region_id: 12, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'ANTOFAGASTA', region_id: 2, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'ANTUCO', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'ARAUCO', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'ARICA', region_id: 15, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'AYSEN', region_id: 11, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'BUIN', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'BULNES', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CAÑETE', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CABILDO', region_id: 5, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CABO DE HORNOS', region_id: 12, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CABRERO', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CALAMA', region_id: 2, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CALBUCO', region_id: 10, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CALDERA', region_id: 3, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CALERA', region_id: 5, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CALERA DE TANGO', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CALLE LARGA', region_id: 5, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CAMARONES', region_id: 1, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CAMIÑA', region_id: 1, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CANELA', region_id: 4, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CARAHUE', region_id: 9, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CARTAGENA', region_id: 5, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CASABLANCA', region_id: 5, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CASTRO', region_id: 10, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CATEMU', region_id: 5, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CAUQUENES', region_id: 7, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CERRILLOS', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CERRO NAVIA', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CHAÑARAL', region_id: 3, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CHAITEN', region_id: 10, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CHANCO', region_id: 7, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CHEPICA', region_id: 6, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CHIGUAYANTE', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CHILE CHICO', region_id: 11, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CHILLAN', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CHILLAN VIEJO', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CHIMBARONGO', region_id: 6, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CHOLCHOL', region_id: 9, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CHONCHI', region_id: 10, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CISNES', region_id: 11, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'COBQUECURA', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'COCHAMO', region_id: 10, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'COCHRANE', region_id: 11, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CODEGUA', region_id: 6, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'COELEMU', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'COIHAIQUE', region_id: 11, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'COIHUECO', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'COINCO', region_id: 6, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'COLBUN', region_id: 7, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'COLCHANE', region_id: 1, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'COLINA', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'COLLIPULLI', region_id: 9, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'COLTAUCO', region_id: 6, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'COMBARBALA', region_id: 4, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CONCEPCION', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CONCHALI', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CONCON', region_id: 5, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CONSTITUCION', region_id: 7, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CONTULMO', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'COPIAPO', region_id: 3, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'COQUIMBO', region_id: 4, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CORONEL', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CORRAL', region_id: 14, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CUNCO', region_id: 9, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CURACAUTIN', region_id: 9, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CURACAVI', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CURACO DE VELEZ', region_id: 10, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CURANILAHUE', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CURARREHUE', region_id: 9, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CUREPTO', region_id: 7, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'CURICO', region_id: 7, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'DALCAHUE', region_id: 10, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'DIEGO DE ALMAGRO', region_id: 3, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'DOÑIHUE', region_id: 6, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'EL BOSQUE', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'EL CARMEN', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'EL MONTE', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'EL OLIVAR', region_id: 6, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'EL QUISCO', region_id: 5, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'EL TABO', region_id: 5, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'EMPEDRADO', region_id: 7, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'ERCILLA', region_id: 9, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'ESTACION CENTRAL', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'FLORIDA', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'FREIRE', region_id: 9, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'FREIRINA', region_id: 3, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'FRESIA', region_id: 10, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'FRUTILLAR', region_id: 10, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'FUTALEUFU', region_id: 10, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'FUTRONO', region_id: 14, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'GALVARINO', region_id: 9, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'GENERAL LAGOS', region_id: 1, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'GORBEA', region_id: 9, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'GRANEROS', region_id: 6, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'GUAITECAS', region_id: 11, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'HIJUELAS', region_id: 5, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'HUALAÑE', region_id: 7, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'HUALAIHUE', region_id: 10, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'HUALPEN', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'HUALQUI', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'HUARA', region_id: 1, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'HUASCO', region_id: 3, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'HUECHURABA', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'ILLAPEL', region_id: 4, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'INDEPENDENCIA', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'IQUIQUE', region_id: 1, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'ISLA DE MAIPO', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'ISLA DE PASCUA', region_id: 5, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'JUAN FERNANDEZ', region_id: 5, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LA CISTERNA', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LA CRUZ', region_id: 5, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LA ESTRELLA', region_id: 6, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LA FLORIDA', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LA GRANJA', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LA HIGUERA', region_id: 4, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LA LIGUA', region_id: 5, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LA PINTANA', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LA REINA', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LA SERENA', region_id: 4, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LA UNION', region_id: 14, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LAGO RANCO', region_id: 14, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LAGO VERDE', region_id: 11, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LAGUNA BLANCA', region_id: 12, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LAJA', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LAMPA', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LANCO', region_id: 14, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LAS CABRAS', region_id: 6, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LAS CONDES', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LAUTARO', region_id: 9, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LEBU', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LICANTEN', region_id: 7, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LIMACHE', region_id: 5, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LINARES', region_id: 7, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LITUECHE', region_id: 6, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LLAILLAY', region_id: 5, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LLANQUIHUE', region_id: 10, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LO BARNECHEA', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LO ESPEJO', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LO PRADO', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LOLOL', region_id: 6, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LONCOCHE', region_id: 9, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LONGAVI', region_id: 7, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LONQUIMAY', region_id: 9, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LOS ALAMOS', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LOS ANDES', region_id: 5, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LOS ANGELES', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LOS LAGOS', region_id: 10, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LOS MUERMOS', region_id: 10, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LOS SAUCES', region_id: 9, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LOS VILOS', region_id: 4, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LOTA', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'LUMACO', region_id: 9, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'MACHALI', region_id: 6, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'MACUL', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'MAFIL', region_id: 14, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'MAIPU', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'MALLOA', region_id: 6, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'MARCHIHUE', region_id: 6, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'MARIA ELENA', region_id: 2, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'MARIA PINTO', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'MARIQUINA', region_id: 14, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'MAULE', region_id: 7, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'MAULLIN', region_id: 10, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'MEJILLONES', region_id: 2, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'MELIPEUCO', region_id: 9, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'MELIPILLA', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'MOLINA', region_id: 7, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'MONTE PATRIA', region_id: 4, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'MOSTAZAL', region_id: 6, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'MULCHEN', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'NACIMIENTO', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'NANCAGUA', region_id: 6, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'NATALES', region_id: 12, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'NAVIDAD', region_id: 6, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'NEGRETE', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'NINHUE', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'NOGALES', region_id: 5, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'NUEVA IMPERIAL', region_id: 9, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'O\'HIGGINS', region_id: 11, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'OLLAGUE', region_id: 2, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'OLMUE', region_id: 5, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'OSORNO', region_id: 10, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'OVALLE', region_id: 4, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PADRE HURTADO', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PADRE LAS CASAS', region_id: 9, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PAIHUANO', region_id: 4, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PAILLACO', region_id: 14, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PAINE', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PALENA', region_id: 10, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PALMILLA', region_id: 6, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PANGUIPULLI', region_id: 14, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PANQUEHUE', region_id: 5, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PAPUDO', region_id: 5, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PAREDONES', region_id: 6, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PARRAL', region_id: 7, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PEÑAFLOR', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PEÑALOLEN', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PEDRO AGUIRRE CERDA', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PELARCO', region_id: 7, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PELLUHUE', region_id: 7, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PEMUCO', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PENCAHUE', region_id: 7, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PENCO', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PERALILLO', region_id: 6, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PERQUENCO', region_id: 9, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PETORCA', region_id: 5, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PEUMO', region_id: 6, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PICA', region_id: 1, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PICHIDEGUA', region_id: 6, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PICHILEMU', region_id: 6, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PINTO', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PIRQUE', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PITRUFQUEN', region_id: 9, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PLACILLA', region_id: 6, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PORTEZUELO', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PORVENIR', region_id: 12, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'POZO ALMONTE', region_id: 1, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PRIMAVERA', region_id: 12, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PROVIDENCIA', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PUCHUNCAVI', region_id: 5, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PUCON', region_id: 9, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PUDAHUEL', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PUENTE ALTO', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PUERTO MONTT', region_id: 10, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PUERTO OCTAY', region_id: 10, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PUERTO VARAS', region_id: 10, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PUMANQUE', region_id: 6, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PUNITAQUI', region_id: 4, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PUNTA ARENAS', region_id: 12, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PUQUELDON', region_id: 10, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PUREN', region_id: 9, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PURRANQUE', region_id: 10, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PUTAENDO', region_id: 5, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PUTRE', region_id: 1, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'PUYEHUE', region_id: 10, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'QUEILEN', region_id: 10, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'QUELLON', region_id: 10, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'QUEMCHI', region_id: 10, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'QUILACO', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'QUILICURA', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'QUILLECO', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'QUILLON', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'QUILLOTA', region_id: 5, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'QUILPUE', region_id: 5, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'QUINCHAO', region_id: 10, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'QUINTA DE TILCOCO', region_id: 6, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'QUINTA NORMAL', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'QUINTERO', region_id: 5, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'QUIRIHUE', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'RANCAGUA', region_id: 6, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'RANQUIL', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'RAUCO', region_id: 7, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'RECOLETA', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'RENAICO', region_id: 9, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'RENCA', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'RENGO', region_id: 6, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'REQUINOA', region_id: 6, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'RETIRO', region_id: 7, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'RINCONADA', region_id: 5, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'RIO BUENO', region_id: 14, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'RIO CLARO', region_id: 7, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'RIO HURTADO', region_id: 4, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'RIO IBAÑEZ', region_id: 11, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'RIO NEGRO', region_id: 10, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'RIO VERDE', region_id: 12, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'ROMERAL', region_id: 7, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'SAAVEDRA', region_id: 9, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'SAGRADA FAMILIA', region_id: 7, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'SALAMANCA', region_id: 4, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'SAN ANTONIO', region_id: 5, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'SAN BERNARDO', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'SAN CARLOS', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'SAN CLEMENTE', region_id: 7, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'SAN ESTEBAN', region_id: 5, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'SAN FABIAN', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'SAN FELIPE', region_id: 5, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'SAN FERNANDO', region_id: 6, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'SAN GREGORIO', region_id: 12, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'SAN IGNACIO', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'SAN JAVIER', region_id: 7, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'SAN JOAQUIN', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'SAN JOSE DE MAIPO', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'SAN JUAN DE LA COSTA', region_id: 10, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'SAN MIGUEL', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'SAN NICOLAS', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'SAN PABLO', region_id: 10, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'SAN PEDRO', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'SAN PEDRO DE ATACAMA', region_id: 2, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'SAN PEDRO DE LA PAZ', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'SAN RAFAEL', region_id: 7, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'SAN RAMON', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'SAN ROSENDO', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'SAN VICENTE', region_id: 6, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'SANTA BARBARA', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'SANTA CRUZ', region_id: 6, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'SANTA JUANA', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'SANTA MARIA', region_id: 5, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'SANTIAGO', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'SANTO DOMINGO', region_id: 5, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'SIERRA GORDA', region_id: 2, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'TALAGANTE', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'TALCA', region_id: 7, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'TALCAHUANO', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'TALTAL', region_id: 2, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'TEMUCO', region_id: 9, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'TENO', region_id: 7, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'TEODORO SCHMIDT', region_id: 9, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'TIERRA AMARILLA', region_id: 3, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'TILTIL', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'TIMAUKEL', region_id: 12, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'TIRUA', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'TOCOPILLA', region_id: 2, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'TOLTEN', region_id: 9, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'TOME', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'TORRES DEL PAINE', region_id: 12, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'TORTEL', region_id: 11, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'TRAIGUEN', region_id: 9, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'TREHUACO', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'TUCAPEL', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'VALDIVIA', region_id: 14, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'VALLENAR', region_id: 3, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'VALPARAISO', region_id: 5, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'VIÑA DEL MAR', region_id: 5, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'VICHUQUEN', region_id: 7, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'VICTORIA', region_id: 9, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'VICUNA', region_id: 4, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'VILCUN', region_id: 9, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'VILLA ALEGRE', region_id: 7, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'VILLA ALEMANA', region_id: 5, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'VILLARRICA', region_id: 9, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'VITACURA', region_id: 13, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'YERBAS BUENAS' , region_id: 7, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'YUMBEL', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'YUNGAY', region_id: 8, id_comuna: id; id+=1
  # Comune.create desc_comuna: 'ZAPALLAR', region_id: 5, id_comuna: id; id+=1
end
