language: ruby
rvm:
# - 2.3 # i'm not indicating ruby version in order to travis look at .ruby-version

env:
  RAILS_ENV=test

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - npm install -g bower
  - bower install

script:
  - bundle exec rspec spec

addons:
  postgresql: "9.4"
